### ISSUE TITLE
Add Catppuccin Mocha Mauve theme?

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [streetwriters/notesnook-themes#77]
@revsuine Saw your Catppuccin Mocha Blue theme and quite enjoyed it, is it possible for you to add the Catppuccin Mocha Mauve theme?

Thanks!

**Comment by revsuine** [comment]
Heya, thank you! I made the theme for my own personal usage and I wanted the blue accent, but you can very easily make a Mauve version by just doing find and replace, replace all instances of `#89b4fa` with `#cba6f7`. Nothing else about the theme needs to be changed, and this replacement only needs to be done on the `theme.json` file (obviously make sure to put your updated `theme.json` in another folder, not the `catppuccin-mocha-blue` folder, otherwise it will overwrite the blue theme). If you create this new theme you can submit a PR so that other people can use the theme too :)
